### ISSUE TITLE
square bracket indexing / subsetting should fail gracefully

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#89]
Fix '[' method for `SoilProfileCollection` objects so that `x[, j]` does not fail or corrupt data when `x` has a profile with less than `j` horizons.

```r
library(aqp)

# simulate some data, IDs are 1:20
set.seed(1010101)
d <- lapply(1:20, random_profile)
d <- do.call('rbind', d )

# init SoilProfilecollection object
depths(d) <- id ~ top + bottom
head(horizons(d))

# differing numbers of horizons
profileApply(d, nrow)

plot(d)
plot(d[, 1:3])
plot(d[, 1:2])
plot(d[, 1:5])

# attempt to extract the nth horizon
plot(d[, 2])
plot(d[, 5])

## this works but the site data are wrong
profile_id(d[, 5])
site(d[, 5])
```

**Comment by brownag** [comment]
The above condition is fixed in aqp/mollic. Propagates j-index constraints to site, diagnostics, restrictions and spatial slots.

Here is a demo:

```
devtools::install_github('ncss-tech/aqp@mollic')
library(aqp)
library(soilDB)

data("loafercreek")

loafercreek <- filter(loafercreek, !is.na(x_std))
coordinates(loafercreek) <- ~ x_std + y_std

# only a few profiles have n=7 or 8 horizons 
# none have 9 or 10
l7 <- loafercreek[,7:10]

par(mar=c(1,1,1,1))
plot(l7)

# here they are
plot(slot(l7, 'sp'))

# 39 sites
nrow(site(l7))

# 39 SpatialPoints
length(slot(l7, 'sp'))

# 127 diagnostic features
nrow(diagnostic_hz(l7))

# 39 unique profile ids in diagnostics
length(unique(diagnostic_hz(l7)[[idname(l7)]]))

# 49 restrictions
nrow(restrictions(l7))

# 39 unique profile ids in restrictions
length(unique(restrictions(l7)[[idname(l7)]]))
```
![image](https://user-images.githubusercontent.com/20842828/82792063-a7886800-9e23-11ea-94e9-c85e58f9f0b1.png)
![image](https://user-images.githubusercontent.com/20842828/82792175-d8689d00-9e23-11ea-8815-89daf6a4d077.png)

**Comment by dylanbeaudette** [comment]
Thanks @brownag, this was a bad bug in need of a fix. If you are convinced that all tests pass (aqp and soilDB with sample data in local NASIS) then I think that we should merge these changes. I can test / review on my personal machine as GH is still broken on work machines.

**Comment by brownag** [comment]
@dylanbeaudette 

aqp and soilDB were passing with R 4.0 on my personal machine last night. I will test soilDB with local NASIS today -- not expecting any surprises. I went through and cleaned up the R CMD CHECK needs for aqp, so it could probably be merged in this evening if all goes according to plan.
